services:
  server:
    build:
      context: .
    command: uvicorn src.evaluator_api.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - PREDICTED_SENTIMENT_COLUMN_NAME=predicted_sentiment
      - MAX_SEQUENCE_LENGTH=512
      - BASE_URL=http://server:8000
      - MODEL=distilbert/distilbert-base-uncased-finetuned-sst-2-english
      - INPUT_TEXT_MAX_LENGTH=2560

  frontend:
    build:
      context: .
    ports:
      - 8501:8501
    environment:
      - BASE_URL=http://server:8000
      - INPUT_TEXT_MAX_LENGTH=2560
    command: streamlit run src/frontend/main.py
    depends_on:
      - server
